version: 2.1
jobs:
  smoke-and-load-test:
    docker:
      - image: google/cloud-sdk
      - image: williamyeh/wrk
    steps:
      - checkout
      - run:
          name: Configure gcloud
          command: |
            echo $GCLOUD_SERVICE_KEY > key.json
            gcloud auth activate-service-account --key-file=key.json
            gcloud container clusters get-credentials whizlabs-cluster --zone us-central1-a --project $GCLOUD_PROJECT_ID
      - run:
          name: Smoke Test
          command: |
            set -e
            URL=$(kubectl get service todo-app -o=jsonpath='{.status.loadBalancer.ingress[0].ip}'):80
            curl --fail $URL
      - run:
          name: Run load tests
          command: |
            wrk -t2 -c10 -d1m $URL
workflows:
  test:
    jobs:
      - smoke-and-load-test:
          context: my-context
