version: 2.1
jobs:
  build:
    docker:
      - image: docker:20.10.11
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Build and push Docker image
          command: |
            docker build -t $DOCKERHUB_USERNAME/todo_app:latest .
            docker push $DOCKERHUB_USERNAME/todo_app:latest
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Configure gcloud
          command: |
            echo $GCLOUD_SERVICE_KEY > key.json
            gcloud auth activate-service-account --key-file=key.json
            gcloud container clusters get-credentials whizlabs-cluster --zone us-central1-a --project $GCLOUD_PROJECT_ID
      - run:
          name: Deploy to Kubernetes
          command: kubectl apply -f Deployment.yaml
  install-kubectl:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - run:
          name: Install kubectl
          command: |
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
      - checkout
  smoke-test:
    docker:
      - image: alpine
    steps:
      - checkout
      - run:
          name: Wait for deployment
          command: kubectl rollout status deployment/todo-app
      - run:
          name: Install dependencies
          command: apk add curl
      - run:
          name: Run smoke tests
          command: |
            set -e
            endpoint=$(kubectl get service todo-app -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
            curl http://$endpoint/healthz
  load-test:
    docker:
      - image: williamyeh/wrk
    steps:
      - checkout
      - run:
          name: Wait for deployment
          command: kubectl rollout status deployment/todo-app
      - run:
          name: Run load tests
          command: |
            set -e
            endpoint=$(kubectl get service todo-app -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
            wrk -t2 -c10 -d1m http://$endpoint
workflows:
  build-and-deploy:
    jobs:
      - build:
          context: my-context
      - deploy:
          context: my-context
      - install-kubectl:
          context: my-context
      - smoke-test:
          context: my-context
      - load-test:
          context: my-context
