version: 2.1
jobs:
  smoke_test:
    docker:
      - image: curlimages/curl:latest
    steps:
      - run:
          name: Wait for deployment to complete
          command: sleep 60
      - run:
          name: Test the application
          command: |
            curl -sSf http://35.223.142.78:80 | grep -q 'Todo App'
  load_test:
    docker:
      - image: node:14.15.4
    steps:
      - checkout
      - run:
          name: Install Load Test Dependencies
          command: |
            npm install -g artillery
      - run:
          name: Run Load Test
          command: |
            artillery quick -r 10 -d 30 http://35.223.142.78:80 
workflows:
  build-and-deploy:
    jobs:
      - smoke_test:
          context: my-context
      - load_test:
          context: my-context
