version: 2.1
jobs:
  smoke_test:
    docker:
      - image: curlimages/curl:latest
    steps:
      - run:
          name: Test the application
          command: |
            curl -sSf http://35.223.142.78:80
  load_test:
    docker:
      - image: williamyeh/wrk
    steps:
      - checkout
      - run:
          name: Run load tests
          command: |
            wrk -t2 -c10 -d1m http://35.223.142.78:80
workflows:
  build-and-deploy:
    jobs:
      - smoke_test:
          context: my-context
      - load_test:
          context: my-context
